Mercy-Collective/mercy-framework

- resources/[mercy]/mercy-business/server/sv_main.lua
When creating a business it auto creates a bank account but does not set a default balance causing the owner to not be able to access the bank just stuck on loading.
> fix(Business/Accounts): Business Account Error

- resources/[essentials]/mercy-ui/nui/Apps/Phone/js/main.js
- resources/[mercy]/mercy-phone/server/sv_contacts.lua
Fixed the incorrect phone number format in some of the phone apps.
Before: https://imgur.com/a/1YfE2jM
After: https://imgur.com/a/LeyeorQ
> fix(Phone/Apps): Phone Number Format

- resources/[essentials]/mercy-ui/config/cl_config.lua
- resources/[mercy]/mercy-jobs/client/jobcenter/cl_sanitation.lua
Fixed not being able to pickup the trash while on the sanitation job and fixed not being able to throw trash in the truck.
> fix(Jobs/Sanitation): PIcking Up Trash & Throwing Trash In Truck

- .gitignore
- resources/[essentials]/mercy-ui/client/cl_characters.lua
- resources/[mercy]/mercy-clothing/client/cl_main.lua
- resources/[mercy]/mercy-vehicles/client/cl_vehHandler.lua
- Fixed steering angle.
- Added off-road handling.
> Adj(Handling): Fixed handling + clothing + Git.ignore changes.

- resources/[essentials]/mercy-base/server/int/sv_main.lua
Fixed the removing crypto module and the has enough crypto callback.
> fix(Base/Crypto): Crypto Callbacks/Modules

- resources/[mercy]/mercy-clothing/client/cl_functions.lua
- resources/[mercy]/mercy-clothing/client/cl_main.lua
- resources/[mercy]/mercy-clothing/nui/index.html
- resources/[mercy]/mercy-clothing/server/sv_main.lua
- Optimized the customs peds
- Fixed the beard coloring typo
- Fixed normal ped cannot saved when load the character
Discord : Space's#8263
> Clothing with better configurations

- resources/[mercy]/mercy-clothing/client/cl_functions.lua
> Typos its my faults

- resources/[mercy]/mercy-clothing/server/sv_main.lua
- Fixed Error when saving skin
> fix(Clothing): Save Skin

- resources/[mercy]/mercy-clothing/client/cl_main.lua
- resources/[mercy]/mercy-clothing/server/sv_main.lua
- resources/[mercy]/mercy-items/server/sv_main.lua
In the previously pull request i made i forgot to change the rest of the code, with this changes the problem with skin model should be resolved.
The problem where you receive multiple phones when opening the Present should be resolved
> Fix Skin Model and Multiple phones on Present Opening

- resources/[essentials]/mercy-ui/nui/Apps/Spawn/js/main.js
- Fixed spam favorites when logout the character
s
> Spam issue when favorites the map

- resources/[mercy]/mercy-business/client/cl_zones.lua
> Fix making burgers

- resources/[mercy]/mercy-misc/client/cl_airdefense.lua
I tested it on my Local server the only thing i changed was the AirstrikeRocket back to to Sniper.
> Airdefense Fix

- frameworkdb.sql
- resources/[mercy]/mercy-phone/config/sh_config.lua
- resources/[mercy]/mercy-phone/server/sv_twitter.lua
- resources/[mercy]/mercy-vehicles/server/sv_main.lua
It should now work perfectly ( When buying car in pdm it wasn't in depot )
> Final Fix Depot || Twitter Save SQL + Auto Delete Tweet

- resources/[essentials]/mercy-ui/client/cl_characters.lua
Characters not spawning everytimes
> Hotfix: cl_characters.lua

- resources/[mercy]/mercy-police/server/sv_main.lua
> Hotfix: Blips Emergency Services

- resources/[mercy]/mercy-chat/client/cl_main.lua
> Hotfix: Mercy-Chat

- resources/[mercy]/mercy-clothing/client/cl_main.lua
I'm using mercy-clothing for qb and I saw that there was a problem loading HairFade and I found a solution to the problem
> Fix HairFade not loading

- resources/[mercy]/mercy-assets/client/cl_props.lua
Was having an issue when using fuel pumps, The anim would get stuck. 
Fixed and commited.
> Fixed issue with anims getting stuck. (props)

- resources/[mercy]/mercy-heists/server/sv_houses.lua
- Fixed the alarm triggering for everyone on the server during a house robbery
> House Robbery

- resources/[mercy]/mercy-business/client/cl_main.lua
- resources/[mercy]/mercy-business/server/sv_foodchain.lua
- resources/[mercy]/mercy-business/shared/sh_config.lua
- resources/[mercy]/mercy-police/server/sv_main.lua
An NPC delivery mission for food businesses to do when they can't find players to fill the role.
> Foodchain delivery

- resources/[mercy]/mercy-heists/client/cl_bank.lua
- resources/[mercy]/mercy-heists/client/cl_banktruck.lua
- resources/[mercy]/mercy-heists/client/cl_bobcat.lua
- resources/[mercy]/mercy-heists/client/cl_jewellery.lua
- resources/[mercy]/mercy-heists/client/cl_stores.lua
- resources/[mercy]/mercy-heists/client/cl_vault.lua
- resources/[mercy]/mercy-phone/client/_cl_main.lua
- resources/[mercy]/mercy-police/client/cl_main.lua
- resources/[mercy]/mercy-police/server/sv_main.lua
- resources/[mercy]/mercy-police/shared/sh_config.lua
A system command for police teams that will prevent robberies when they are not available.
> Added "secure" for cops

- resources/[mercy]/mercy-doors/client/cl_main.lua
Double doors now lock/unlock together.
> Update connected doors together.
